# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(496, 434)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.txtResult = QtWidgets.QTextEdit(self.centralwidget)
        self.txtResult.setReadOnly(True)
        self.txtResult.setObjectName("txtResult")
        self.gridLayout.addWidget(self.txtResult, 0, 0, 1, 1)
        self.txtOperando = QtWidgets.QLineEdit(self.centralwidget)
        self.txtOperando.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txtOperando.setStyleSheet("text-align: right;")
        self.txtOperando.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txtOperando.setInputMask("")
        self.txtOperando.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.txtOperando.setObjectName("txtOperando")
        self.gridLayout.addWidget(self.txtOperando, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnSqrt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSqrt.sizePolicy().hasHeightForWidth())
        self.btnSqrt.setSizePolicy(sizePolicy)
        self.btnSqrt.setMaximumSize(QtCore.QSize(54, 45))
        self.btnSqrt.setObjectName("btnSqrt")
        self.gridLayout_2.addWidget(self.btnSqrt, 0, 0, 1, 1)
        self.btnPow = QtWidgets.QPushButton(self.centralwidget)
        self.btnPow.setMaximumSize(QtCore.QSize(54, 45))
        self.btnPow.setObjectName("btnPow")
        self.gridLayout_2.addWidget(self.btnPow, 0, 1, 1, 1)
        self.btnMod = QtWidgets.QPushButton(self.centralwidget)
        self.btnMod.setMaximumSize(QtCore.QSize(54, 45))
        self.btnMod.setObjectName("btnMod")
        self.gridLayout_2.addWidget(self.btnMod, 0, 3, 1, 1)
        self.btnNotacion = QtWidgets.QPushButton(self.centralwidget)
        self.btnNotacion.setMaximumSize(QtCore.QSize(54, 45))
        self.btnNotacion.setObjectName("btnNotacion")
        self.gridLayout_2.addWidget(self.btnNotacion, 0, 2, 1, 1)
        self.btnSinh = QtWidgets.QPushButton(self.centralwidget)
        self.btnSinh.setMaximumSize(QtCore.QSize(54, 45))
        self.btnSinh.setObjectName("btnSinh")
        self.gridLayout_2.addWidget(self.btnSinh, 2, 6, 1, 1)
        self.btnOcho = QtWidgets.QPushButton(self.centralwidget)
        self.btnOcho.setMaximumSize(QtCore.QSize(54, 45))
        self.btnOcho.setObjectName("btnOcho")
        self.gridLayout_2.addWidget(self.btnOcho, 1, 1, 1, 1)
        self.btnPunto = QtWidgets.QPushButton(self.centralwidget)
        self.btnPunto.setMaximumSize(QtCore.QSize(54, 45))
        self.btnPunto.setObjectName("btnPunto")
        self.gridLayout_2.addWidget(self.btnPunto, 4, 1, 1, 1)
        self.btnDos = QtWidgets.QPushButton(self.centralwidget)
        self.btnDos.setMaximumSize(QtCore.QSize(54, 45))
        self.btnDos.setObjectName("btnDos")
        self.gridLayout_2.addWidget(self.btnDos, 3, 1, 1, 1)
        self.btnIgual = QtWidgets.QPushButton(self.centralwidget)
        self.btnIgual.setMaximumSize(QtCore.QSize(54, 45))
        self.btnIgual.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"color: white;")
        self.btnIgual.setObjectName("btnIgual")
        self.gridLayout_2.addWidget(self.btnIgual, 4, 4, 1, 1)
        self.btnSiete = QtWidgets.QPushButton(self.centralwidget)
        self.btnSiete.setMaximumSize(QtCore.QSize(54, 45))
        self.btnSiete.setObjectName("btnSiete")
        self.gridLayout_2.addWidget(self.btnSiete, 1, 0, 1, 1)
        self.btnEntre = QtWidgets.QPushButton(self.centralwidget)
        self.btnEntre.setMaximumSize(QtCore.QSize(54, 45))
        self.btnEntre.setObjectName("btnEntre")
        self.gridLayout_2.addWidget(self.btnEntre, 1, 3, 1, 1)
        self.btnTres = QtWidgets.QPushButton(self.centralwidget)
        self.btnTres.setMaximumSize(QtCore.QSize(54, 45))
        self.btnTres.setObjectName("btnTres")
        self.gridLayout_2.addWidget(self.btnTres, 3, 2, 1, 1)
        self.btnTan = QtWidgets.QPushButton(self.centralwidget)
        self.btnTan.setMaximumSize(QtCore.QSize(54, 45))
        self.btnTan.setObjectName("btnTan")
        self.gridLayout_2.addWidget(self.btnTan, 2, 5, 1, 1)
        self.btnFactorial = QtWidgets.QPushButton(self.centralwidget)
        self.btnFactorial.setMaximumSize(QtCore.QSize(54, 45))
        self.btnFactorial.setObjectName("btnFactorial")
        self.gridLayout_2.addWidget(self.btnFactorial, 4, 6, 1, 1)
        self.btnTanh = QtWidgets.QPushButton(self.centralwidget)
        self.btnTanh.setMaximumSize(QtCore.QSize(54, 45))
        self.btnTanh.setObjectName("btnTanh")
        self.gridLayout_2.addWidget(self.btnTanh, 3, 6, 1, 1)
        self.btnUno = QtWidgets.QPushButton(self.centralwidget)
        self.btnUno.setMaximumSize(QtCore.QSize(54, 45))
        self.btnUno.setObjectName("btnUno")
        self.gridLayout_2.addWidget(self.btnUno, 3, 0, 1, 1)
        self.btnCuatro = QtWidgets.QPushButton(self.centralwidget)
        self.btnCuatro.setMaximumSize(QtCore.QSize(54, 45))
        self.btnCuatro.setObjectName("btnCuatro")
        self.gridLayout_2.addWidget(self.btnCuatro, 2, 0, 1, 1)
        self.btnNueve = QtWidgets.QPushButton(self.centralwidget)
        self.btnNueve.setMaximumSize(QtCore.QSize(54, 45))
        self.btnNueve.setObjectName("btnNueve")
        self.gridLayout_2.addWidget(self.btnNueve, 1, 2, 1, 1)
        self.btnAsin = QtWidgets.QPushButton(self.centralwidget)
        self.btnAsin.setMaximumSize(QtCore.QSize(54, 45))
        self.btnAsin.setObjectName("btnAsin")
        self.gridLayout_2.addWidget(self.btnAsin, 4, 5, 1, 1)
        self.btnCinco = QtWidgets.QPushButton(self.centralwidget)
        self.btnCinco.setMaximumSize(QtCore.QSize(54, 45))
        self.btnCinco.setObjectName("btnCinco")
        self.gridLayout_2.addWidget(self.btnCinco, 2, 1, 1, 1)
        self.btnLog = QtWidgets.QPushButton(self.centralwidget)
        self.btnLog.setMaximumSize(QtCore.QSize(54, 45))
        self.btnLog.setObjectName("btnLog")
        self.gridLayout_2.addWidget(self.btnLog, 2, 7, 1, 1)
        self.btnParentesis = QtWidgets.QPushButton(self.centralwidget)
        self.btnParentesis.setMaximumSize(QtCore.QSize(54, 45))
        self.btnParentesis.setObjectName("btnParentesis")
        self.gridLayout_2.addWidget(self.btnParentesis, 4, 2, 1, 1)
        self.btnFactorizar = QtWidgets.QPushButton(self.centralwidget)
        self.btnFactorizar.setMaximumSize(QtCore.QSize(54, 45))
        self.btnFactorizar.setObjectName("btnFactorizar")
        self.gridLayout_2.addWidget(self.btnFactorizar, 1, 4, 1, 1)
        self.btnAtan = QtWidgets.QPushButton(self.centralwidget)
        self.btnAtan.setMaximumSize(QtCore.QSize(54, 45))
        self.btnAtan.setObjectName("btnAtan")
        self.gridLayout_2.addWidget(self.btnAtan, 0, 6, 1, 1)
        self.btnCos = QtWidgets.QPushButton(self.centralwidget)
        self.btnCos.setMaximumSize(QtCore.QSize(54, 45))
        self.btnCos.setObjectName("btnCos")
        self.gridLayout_2.addWidget(self.btnCos, 0, 5, 1, 1)
        self.btnPi = QtWidgets.QPushButton(self.centralwidget)
        self.btnPi.setMaximumSize(QtCore.QSize(54, 45))
        self.btnPi.setObjectName("btnPi")
        self.gridLayout_2.addWidget(self.btnPi, 3, 4, 1, 1)
        self.btnSimplificar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSimplificar.setMaximumSize(QtCore.QSize(54, 45))
        self.btnSimplificar.setObjectName("btnSimplificar")
        self.gridLayout_2.addWidget(self.btnSimplificar, 0, 4, 1, 1)
        self.btnExp = QtWidgets.QPushButton(self.centralwidget)
        self.btnExp.setMaximumSize(QtCore.QSize(54, 45))
        self.btnExp.setObjectName("btnExp")
        self.gridLayout_2.addWidget(self.btnExp, 2, 4, 1, 1)
        self.btnCosh = QtWidgets.QPushButton(self.centralwidget)
        self.btnCosh.setMaximumSize(QtCore.QSize(54, 45))
        self.btnCosh.setObjectName("btnCosh")
        self.gridLayout_2.addWidget(self.btnCosh, 1, 6, 1, 1)
        self.btnSin = QtWidgets.QPushButton(self.centralwidget)
        self.btnSin.setMaximumSize(QtCore.QSize(54, 45))
        self.btnSin.setObjectName("btnSin")
        self.gridLayout_2.addWidget(self.btnSin, 1, 5, 1, 1)
        self.btnMenos = QtWidgets.QPushButton(self.centralwidget)
        self.btnMenos.setMaximumSize(QtCore.QSize(54, 45))
        self.btnMenos.setObjectName("btnMenos")
        self.gridLayout_2.addWidget(self.btnMenos, 3, 3, 1, 1)
        self.btnSeis = QtWidgets.QPushButton(self.centralwidget)
        self.btnSeis.setMaximumSize(QtCore.QSize(54, 45))
        self.btnSeis.setObjectName("btnSeis")
        self.gridLayout_2.addWidget(self.btnSeis, 2, 2, 1, 1)
        self.btnCero = QtWidgets.QPushButton(self.centralwidget)
        self.btnCero.setMaximumSize(QtCore.QSize(54, 45))
        self.btnCero.setObjectName("btnCero")
        self.gridLayout_2.addWidget(self.btnCero, 4, 0, 1, 1)
        self.btnAcos = QtWidgets.QPushButton(self.centralwidget)
        self.btnAcos.setMaximumSize(QtCore.QSize(54, 45))
        self.btnAcos.setObjectName("btnAcos")
        self.gridLayout_2.addWidget(self.btnAcos, 3, 5, 1, 1)
        self.btnPor = QtWidgets.QPushButton(self.centralwidget)
        self.btnPor.setMaximumSize(QtCore.QSize(54, 45))
        self.btnPor.setObjectName("btnPor")
        self.gridLayout_2.addWidget(self.btnPor, 2, 3, 1, 1)
        self.btnLn = QtWidgets.QPushButton(self.centralwidget)
        self.btnLn.setMaximumSize(QtCore.QSize(54, 45))
        self.btnLn.setObjectName("btnLn")
        self.gridLayout_2.addWidget(self.btnLn, 1, 7, 1, 1)
        self.btnAbs = QtWidgets.QPushButton(self.centralwidget)
        self.btnAbs.setMaximumSize(QtCore.QSize(54, 45))
        self.btnAbs.setObjectName("btnAbs")
        self.gridLayout_2.addWidget(self.btnAbs, 0, 7, 1, 1)
        self.btnMas = QtWidgets.QPushButton(self.centralwidget)
        self.btnMas.setMaximumSize(QtCore.QSize(54, 45))
        self.btnMas.setObjectName("btnMas")
        self.gridLayout_2.addWidget(self.btnMas, 4, 3, 1, 1)
        self.btnDerivar = QtWidgets.QPushButton(self.centralwidget)
        self.btnDerivar.setMaximumSize(QtCore.QSize(54, 45))
        self.btnDerivar.setObjectName("btnDerivar")
        self.gridLayout_2.addWidget(self.btnDerivar, 3, 7, 1, 1)
        self.btnIntegrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnIntegrar.setMaximumSize(QtCore.QSize(54, 45))
        self.btnIntegrar.setObjectName("btnIntegrar")
        self.gridLayout_2.addWidget(self.btnIntegrar, 4, 7, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txtOperando, self.btnIgual)
        MainWindow.setTabOrder(self.btnIgual, self.btnPow)
        MainWindow.setTabOrder(self.btnPow, self.btnNotacion)
        MainWindow.setTabOrder(self.btnNotacion, self.btnMod)
        MainWindow.setTabOrder(self.btnMod, self.btnSiete)
        MainWindow.setTabOrder(self.btnSiete, self.btnOcho)
        MainWindow.setTabOrder(self.btnOcho, self.btnNueve)
        MainWindow.setTabOrder(self.btnNueve, self.btnEntre)
        MainWindow.setTabOrder(self.btnEntre, self.btnCuatro)
        MainWindow.setTabOrder(self.btnCuatro, self.btnUno)
        MainWindow.setTabOrder(self.btnUno, self.btnCero)
        MainWindow.setTabOrder(self.btnCero, self.btnCinco)
        MainWindow.setTabOrder(self.btnCinco, self.btnDos)
        MainWindow.setTabOrder(self.btnDos, self.btnPunto)
        MainWindow.setTabOrder(self.btnPunto, self.btnSeis)
        MainWindow.setTabOrder(self.btnSeis, self.btnTres)
        MainWindow.setTabOrder(self.btnTres, self.btnPor)
        MainWindow.setTabOrder(self.btnPor, self.btnMenos)
        MainWindow.setTabOrder(self.btnMenos, self.btnMas)
        MainWindow.setTabOrder(self.btnMas, self.btnParentesis)
        MainWindow.setTabOrder(self.btnParentesis, self.btnSimplificar)
        MainWindow.setTabOrder(self.btnSimplificar, self.btnSqrt)
        MainWindow.setTabOrder(self.btnSqrt, self.btnPi)
        MainWindow.setTabOrder(self.btnPi, self.btnExp)
        MainWindow.setTabOrder(self.btnExp, self.btnFactorizar)
        MainWindow.setTabOrder(self.btnFactorizar, self.btnCos)
        MainWindow.setTabOrder(self.btnCos, self.btnSin)
        MainWindow.setTabOrder(self.btnSin, self.btnTan)
        MainWindow.setTabOrder(self.btnTan, self.btnAcos)
        MainWindow.setTabOrder(self.btnAcos, self.btnAsin)
        MainWindow.setTabOrder(self.btnAsin, self.btnAtan)
        MainWindow.setTabOrder(self.btnAtan, self.btnCosh)
        MainWindow.setTabOrder(self.btnCosh, self.btnSinh)
        MainWindow.setTabOrder(self.btnSinh, self.btnTanh)
        MainWindow.setTabOrder(self.btnTanh, self.btnFactorial)
        MainWindow.setTabOrder(self.btnFactorial, self.btnAbs)
        MainWindow.setTabOrder(self.btnAbs, self.btnLn)
        MainWindow.setTabOrder(self.btnLn, self.btnLog)
        MainWindow.setTabOrder(self.btnLog, self.btnDerivar)
        MainWindow.setTabOrder(self.btnDerivar, self.btnIntegrar)
        MainWindow.setTabOrder(self.btnIntegrar, self.txtResult)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyCalc"))
        self.btnSqrt.setText(_translate("MainWindow", "√"))
        self.btnPow.setText(_translate("MainWindow", "x^y"))
        self.btnMod.setText(_translate("MainWindow", "mod"))
        self.btnNotacion.setText(_translate("MainWindow", "10^x"))
        self.btnSinh.setText(_translate("MainWindow", "sinh"))
        self.btnOcho.setText(_translate("MainWindow", "8"))
        self.btnPunto.setText(_translate("MainWindow", "."))
        self.btnDos.setText(_translate("MainWindow", "2"))
        self.btnIgual.setText(_translate("MainWindow", "="))
        self.btnSiete.setText(_translate("MainWindow", "7"))
        self.btnEntre.setText(_translate("MainWindow", "÷"))
        self.btnTres.setText(_translate("MainWindow", "3"))
        self.btnTan.setText(_translate("MainWindow", "tan"))
        self.btnFactorial.setText(_translate("MainWindow", "x!"))
        self.btnTanh.setText(_translate("MainWindow", "tanh"))
        self.btnUno.setText(_translate("MainWindow", "1"))
        self.btnCuatro.setText(_translate("MainWindow", "4"))
        self.btnNueve.setText(_translate("MainWindow", "9"))
        self.btnAsin.setText(_translate("MainWindow", "asin"))
        self.btnCinco.setText(_translate("MainWindow", "5"))
        self.btnLog.setText(_translate("MainWindow", "log"))
        self.btnParentesis.setText(_translate("MainWindow", "( )"))
        self.btnFactorizar.setText(_translate("MainWindow", "fact"))
        self.btnAtan.setText(_translate("MainWindow", "atan"))
        self.btnCos.setText(_translate("MainWindow", "cos"))
        self.btnPi.setText(_translate("MainWindow", "π"))
        self.btnSimplificar.setText(_translate("MainWindow", "simp"))
        self.btnExp.setText(_translate("MainWindow", "e^x"))
        self.btnCosh.setText(_translate("MainWindow", "cosh"))
        self.btnSin.setText(_translate("MainWindow", "sin"))
        self.btnMenos.setText(_translate("MainWindow", "-"))
        self.btnSeis.setText(_translate("MainWindow", "6"))
        self.btnCero.setText(_translate("MainWindow", "0"))
        self.btnAcos.setText(_translate("MainWindow", "acos"))
        self.btnPor.setText(_translate("MainWindow", "x"))
        self.btnLn.setText(_translate("MainWindow", "ln"))
        self.btnAbs.setText(_translate("MainWindow", "|x|"))
        self.btnMas.setText(_translate("MainWindow", "+"))
        self.btnDerivar.setText(_translate("MainWindow", "d/dx"))
        self.btnIntegrar.setText(_translate("MainWindow", "∫"))
        

